package lambda;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.ArrayList;

@DynamoDBTable(tableName = "userTest")
public class RequestUserTest {
    private String id;
    private String candidate;
    private String testID;
    private String recruiter;
    private int state;
    @DynamoDBIgnore
    private ArrayList<String> message;

    public RequestUserTest() {
        this.message = new ArrayList<>();
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "candidate")
    public String getCandidate() {
        return candidate;
    }

    public void setCandidate(String candidate) {
        this.candidate = candidate;
    }

    @DynamoDBAttribute(attributeName = "testID")
    public String getTestID() {
        return testID;
    }

    public void setTestID(String testID) {
        this.testID = testID;
    }

    @DynamoDBAttribute(attributeName = "recruiter")
    public String getRecruiter() {
        return recruiter;
    }

    public void setRecruiter(String recruiter) {
        this.recruiter = recruiter;
    }

    @DynamoDBAttribute(attributeName = "stateTest")
    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    @DynamoDBIgnore
    boolean isCorrect(){
        if(this.candidate.equals("")) message.add("Empty candidate");
        if(this.testID.equals("")) message.add("Empty testID");
        if(this.recruiter.equals("")) message.add("Empty recruiter");
        if (message.size() == 0) {
            message.add("Data is correct");
            return true;
        } else {
            message.add(0,"Data is incorrect");
            return false;
        }
    }
}
